/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotelmanagementsystem;

import controller.datareservecontroller;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author User
 */
public class userCheckIn extends javax.swing.JFrame {

    datareservecontroller dc;
    /**
     * Creates new form custCheckIn
     */
    public userCheckIn() {
        initComponents();
        
        setLocationRelativeTo(null);
        dc = new datareservecontroller(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextPhoneNumber = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboGender = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextIDProof = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextAddress = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextCheckinDate = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jComboRoomType = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jComboBedSize = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jComboRoomNumber = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jTextPrice = new javax.swing.JTextField();
        btnReserve = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(50, 118));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rooms.png"))); // NOI18N
        jLabel1.setText("CHECK IN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 23, -1, -1));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 170, -1, -1));

        jTextName.setBackground(new java.awt.Color(255, 255, 255));
        jTextName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextName, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 199, 300, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Phone Number");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 244, -1, -1));

        jTextPhoneNumber.setBackground(new java.awt.Color(255, 255, 255));
        jTextPhoneNumber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextPhoneNumber.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jTextPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 273, 300, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Gender");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 318, -1, -1));

        jComboGender.setBackground(new java.awt.Color(255, 255, 255));
        jComboGender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboGender.setForeground(new java.awt.Color(0, 0, 0));
        jComboGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        getContentPane().add(jComboGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 347, 300, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Email");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 392, -1, -1));

        jTextEmail.setBackground(new java.awt.Color(255, 255, 255));
        jTextEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextEmail.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jTextEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 421, 300, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ID Proof");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 170, -1, -1));

        jTextIDProof.setBackground(new java.awt.Color(255, 255, 255));
        jTextIDProof.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextIDProof.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jTextIDProof, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 199, 300, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Address");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 244, -1, -1));

        jTextAddress.setBackground(new java.awt.Color(255, 255, 255));
        jTextAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextAddress.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jTextAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 273, 300, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Check-In Date (Today)");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 318, -1, -1));

        jTextCheckinDate.setEditable(false);
        jTextCheckinDate.setBackground(new java.awt.Color(255, 255, 255));
        jTextCheckinDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextCheckinDate.setForeground(new java.awt.Color(0, 0, 0));
        jTextCheckinDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCheckinDateActionPerformed(evt);
            }
        });
        getContentPane().add(jTextCheckinDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 347, 300, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Bed Size");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(839, 244, -1, -1));

        jComboRoomType.setBackground(new java.awt.Color(255, 255, 255));
        jComboRoomType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboRoomType.setForeground(new java.awt.Color(0, 0, 0));
        jComboRoomType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "Non-AC" }));
        getContentPane().add(jComboRoomType, new org.netbeans.lib.awtextra.AbsoluteConstraints(839, 199, 300, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Room Type");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(839, 170, -1, -1));

        jComboBedSize.setBackground(new java.awt.Color(255, 255, 255));
        jComboBedSize.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBedSize.setForeground(new java.awt.Color(0, 0, 0));
        jComboBedSize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double", "King Size" }));
        jComboBedSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBedSizeActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBedSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(839, 273, 300, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Room Number");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(839, 318, -1, -1));

        jComboRoomNumber.setBackground(new java.awt.Color(255, 255, 255));
        jComboRoomNumber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboRoomNumber.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jComboRoomNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(839, 347, 300, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Price");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(839, 392, -1, -1));

        jTextPrice.setBackground(new java.awt.Color(255, 255, 255));
        jTextPrice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextPrice.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jTextPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(839, 421, 300, -1));

        btnReserve.setBackground(new java.awt.Color(255, 255, 255));
        btnReserve.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnReserve.setForeground(new java.awt.Color(0, 0, 0));
        btnReserve.setText("Reserve Room");
        btnReserve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReserveActionPerformed(evt);
            }
        });
        getContentPane().add(btnReserve, new org.netbeans.lib.awtextra.AbsoluteConstraints(839, 466, -1, -1));

        btnClear.setBackground(new java.awt.Color(255, 255, 255));
        btnClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(0, 0, 0));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(1026, 466, -1, -1));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bgHome.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReserveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReserveActionPerformed
        // TODO add your handling code here:
        dc.reserve();
    }//GEN-LAST:event_btnReserveActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        jTextName.setText("");
        jTextAddress.setText("");
        jTextEmail.setText("");
        jTextPhoneNumber.setText("");
        jTextIDProof.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void jComboBedSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBedSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBedSizeActionPerformed

    private void jTextCheckinDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCheckinDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCheckinDateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userCheckIn().setVisible(true);
            }
        });
    }

    public JComboBox<String> getjComboBedSize() {
        return jComboBedSize;
    }

    public void setjComboBedSize(JComboBox<String> jComboBedSize) {
        this.jComboBedSize = jComboBedSize;
    }

    public JComboBox<String> getjComboGender() {
        return jComboGender;
    }

    public void setjComboGender(JComboBox<String> jComboGender) {
        this.jComboGender = jComboGender;
    }

    public JComboBox<String> getjComboRoomNumber() {
        return jComboRoomNumber;
    }

    public void setjComboRoomNumber(JComboBox<String> jComboRoomNumber) {
        this.jComboRoomNumber = jComboRoomNumber;
    }

    public JComboBox<String> getjComboRoomType() {
        return jComboRoomType;
    }

    public void setjComboRoomType(JComboBox<String> jComboRoomType) {
        this.jComboRoomType = jComboRoomType;
    }

    public JTextField getjTextAddress() {
        return jTextAddress;
    }

    public void setjTextAddress(JTextField jTextAddress) {
        this.jTextAddress = jTextAddress;
    }

    public JTextField getjTextCheckinDate() {
        return jTextCheckinDate;
    }

    public void setjTextCheckinDate(String date) {
        this.jTextCheckinDate.setText(date);
    }

    public JTextField getjTextEmail() {
        return jTextEmail;
    }

    public void setjTextEmail(JTextField jTextEmail) {
        this.jTextEmail = jTextEmail;
    }

    public JTextField getjTextIDProof() {
        return jTextIDProof;
    }

    public void setjTextIDProof(JTextField jTextIDProof) {
        this.jTextIDProof = jTextIDProof;
    }

    public JTextField getjTextPhoneNumber() {
        return jTextPhoneNumber;
    }

    public void setjTextPhoneNumber(JTextField jTextPhoneNumber) {
        this.jTextPhoneNumber = jTextPhoneNumber;
    }

    public JTextField getjTextName() {
        return jTextName;
    }

    public void setjTextName(JTextField jTextName) {
        this.jTextName = jTextName;
    }

    public JTextField getjTextPrice() {
        return jTextPrice;
    }

    public void setjTextPrice(JTextField jTextPrice) {
        this.jTextPrice = jTextPrice;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnReserve;
    private javax.swing.JComboBox<String> jComboBedSize;
    private javax.swing.JComboBox<String> jComboGender;
    private javax.swing.JComboBox<String> jComboRoomNumber;
    private javax.swing.JComboBox<String> jComboRoomType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextAddress;
    private javax.swing.JTextField jTextCheckinDate;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextIDProof;
    private javax.swing.JTextField jTextName;
    private javax.swing.JTextField jTextPhoneNumber;
    private javax.swing.JTextField jTextPrice;
    // End of variables declaration//GEN-END:variables
}
